apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 326105981041.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 326105981041.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 109ff267
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
